FROM ubuntu:trusty
MAINTAINER Michael Russell

# Upgrade base system packages
RUN apt-get update

# install freeradius
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --force-yes --no-install-recommends \
    freeradius freeradius-utils freeradius-mysql

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 1812/udp
EXPOSE 1813/udp

CMD /usr/sbin/freeradius -f -xx

